name: APK_Uretici
on: [push] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build_APK
        uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          buildozer_version: master
